#
# Digital Voice Modem - Bridge
#
# @package DVM / Bridge
#

# Time in seconds between pings to peers.
pingTime: 5
# Flag indicating whether or not the router should debug display all packets received.
rawPacketTrace: false

# PCM audio gain for received (from digital network) audio frames.
#   - This is used to apply gain to the decoded IMBE/AMBE audio, post-decoding.
rxAudioGain: 1.0
# Vocoder audio gain for decoded (from digital network) audio frames.
#   - This is used to apply gain to the decoded IMBE/AMBE audio in the vocoder.
#   - (Not used when utilizing external USB vocoder!)
vocoderDecoderAudioGain: 3.0
# Flag indicating AGC should be used for frames received/decoded.
#   - This is used to apply automatic gain control to decoded IMBE/AMBE audio in the vocoder.
#   - (Not used when utilizing external USB vocoder!)
vocoderDecoderAutoGain: false

# PCM audio gain for transmitted (to digital network) audio frames.
#   - This is used to apply gain to the encoded IMBE/AMBE audio, pre-encoding.
txAudioGain: 1.0
# Vocoder audio gain for transmitted/encoded (to digital network) audio frames.
#   - This is used to apply gain to the encoded IMBE/AMBE audio in the vocoder.
#   - (Not used when utilizing external USB vocoder!)
vocoderEncoderAudioGain: 3.0

# Audio transmit mode (1 - DMR, 2 - P25).
txMode: 2

# Relative sample level for VOX to activate.
voxSampleLevel: 30.0

# Flag indicating whether a network grant demand packet will be sent before audio.
grantDemand: true

# Consumer zello username
zelloUsername: "user"
# Consumer zello password
zelloPassword: "password"

#
# Zello Tokens are a pain. They are only used for consumer zello. Dev key is easiest to play with.
#

# Consumer zello auth token. This is the developer token. Good for 30 days. Uncomment to use.
#zelloAuthToken: ""

# Consumer zello issuer. Uncomment to use
#zelloIssuer: ""
# Zello Pem File Path. Uncomment to use
#zelloPemFilePath: "./key.pem"
# Consumer zello channel

# Zello Ping Interval for keep alive
zelloPingInterval: 10000
#Zello Channel name
zelloChannel: "channel"
# Zello rid <-> zello display name alias file. (Leave empty if not wanted)
zelloAliasFile: "./alias.yml"
# Zello websocket URL. Leave alone if for consumer zello. For work the format is wss://zellowork.io/ws/<your network name>
zelloUrl: "wss://zello.io/ws"

# Textual Name
name: BRIDGE
# Network Peer ID
peerId: 99990
# Hostname/IP address of FNE master to connect to.
address: 127.0.0.1
# Port number to connect to.
port: 62030
# FNE access password.
passphrase: PASSWORD

# Flag indicating whether or not FNE encryption is enabled.
encrypted: false
# Preshared AES key for FNE encryption.
presharedKey: "000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F"

# Source "Radio ID" for transmitted audio frames.
sourceId: 1234567
# Flag indicating the source "Radio ID" will be overridden from the received
# UDP SRC ID.
overrideSourceIdFromUDP: true
# Talkgroup ID for transmitted/received audio frames.
destinationId: 2001
# Slot for received/transmitted audio frames.
slot: 1

#
# Logging Configuration
#   Logging Levels:
#     1 - Debug
#     2 - Message
#     3 - Informational
#     4 - Warning
#     5 - Error
#     6 - Fatal
#
log:
    # Console display logging level (used when in foreground).
    displayLevel: 1
    # File logging level.
    fileLevel: 1
    # Full path for the directory to store the log files.
    filePath: .
    # Log filename prefix.
    fileRoot: dvmbridge
